#! /usr/bin/ruby

require 'entry_table_view.rb'
require 'accounts_models.rb'

# connect to the database
ActiveRecord::Base.establish_connection({
  :adapter  => 'postgresql',
  :database => ARGV[0] || 'accounts',
  :host => ARGV[1] || 'localhost',
  :username => 'panic',
  :password => ''
})

puts "using database #{ActiveRecord::Base.connection.raw_connection.db}"

app = Qt::Application.new( ARGV )

def accounts
  EntryTableView.new( Account ).create_model do |t|
    t.plain :name
    t.plain :vat
    t.plain :account_type
    t.plain :pastel_number
    t.plain :fringe
    t.plain :active
    
    t.collection = Account.find( :all, :order => 'id' )
  end
end

def transactions
  EntryTableView.new( Entry ).create_model do |t|
    t.plain       :date, :sample => '28-Dec-08'
    t.distinct    :description, :sample => '12345678901234567890123456'
    t.relational  :debit, 'name', :sample => 'Leilani Member Loan', :class_name => 'Account', :conditions => 'active = true', :order => 'lower(name)'
    t.relational  :credit, 'name', :sample => 'Leilani Member Loan', :class_name => 'Account', :conditions => 'active = true', :order => 'lower(name)'
    t.plain       :amount, :sample => '100000.00'
    t.plain       :cheque_number, :sample => '0000'
    t.plain       :active, :sample => 'Active'
    t.plain       :vat, :sample => 'VAT', :label => 'VAT'
    
    t.collection = Entry.find( :all, :order => 'date, id' )
  end
end

table = transactions
#table = accounts

table.minimum_width = 800
table.show
#~ table.show_maximized

begin
  app.exec
rescue Exception => e
  puts e.backtrace.join( "\n" )
  puts e.message
end
