/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SearchDialog.java
 *
 * Created on Jul 31, 2010, 1:51:54 PM
 */

/**
 *
 * @author panic
 */
public class SearchDialog extends javax.swing.JDialog {

    /** Creates new form SearchDialog */
    public SearchDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        direction_button_group = new javax.swing.ButtonGroup();
        search_label = new javax.swing.JLabel();
        search_combo = new javax.swing.JComboBox();
        from_start = new javax.swing.JCheckBox();
        regex = new javax.swing.JCheckBox();
        whole_words = new javax.swing.JCheckBox();
        forwards = new javax.swing.JRadioButton();
        backwards = new javax.swing.JRadioButton();
        ok_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();

        setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        setName("SearchDialog"); // NOI18N

        search_label.setText("Search"); // NOI18N
        search_label.setName("search_label"); // NOI18N

        search_combo.setEditable(true);
        search_combo.setName("search_combo"); // NOI18N

        from_start.setMnemonic('F');
        from_start.setText("From Start"); // NOI18N
        from_start.setName("from_start"); // NOI18N

        regex.setMnemonic('R');
        regex.setText("Regular Expression"); // NOI18N
        regex.setName("regex"); // NOI18N

        whole_words.setMnemonic('W');
        whole_words.setText("Whole words"); // NOI18N
        whole_words.setName("whole_words"); // NOI18N

        direction_button_group.add(forwards);
        forwards.setMnemonic('F');
        forwards.setText("Forwards"); // NOI18N
        forwards.setName("forwards"); // NOI18N

        direction_button_group.add(backwards);
        backwards.setMnemonic('B');
        backwards.setText("Backwards"); // NOI18N
        backwards.setName("backwards"); // NOI18N

        ok_button.setMnemonic('O');
        ok_button.setText("OK"); // NOI18N
        ok_button.setName("ok_button"); // NOI18N

        cancel_button.setMnemonic('C');
        cancel_button.setText("Cancel"); // NOI18N
        cancel_button.setName("cancel_button"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(21, 21, 21)
                        .add(search_label)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(search_combo, 0, 192, Short.MAX_VALUE)
                            .add(from_start, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(regex, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(whole_words, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(forwards, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(backwards)))
                    .add(layout.createSequentialGroup()
                        .add(ok_button)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 160, Short.MAX_VALUE)
                        .add(cancel_button)))
                .add(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(search_combo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(search_label))
                .add(18, 18, 18)
                .add(from_start)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(regex)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(whole_words)
                .add(18, 18, 18)
                .add(forwards)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(backwards)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(ok_button)
                    .add(cancel_button))
                .add(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                javax.swing.JDialog dialog = new javax.swing.JDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton backwards;
    public javax.swing.JButton cancel_button;
    public javax.swing.ButtonGroup direction_button_group;
    public javax.swing.JRadioButton forwards;
    public javax.swing.JCheckBox from_start;
    public javax.swing.JButton ok_button;
    public javax.swing.JCheckBox regex;
    public javax.swing.JComboBox search_combo;
    public javax.swing.JLabel search_label;
    public javax.swing.JCheckBox whole_words;
    // End of variables declaration//GEN-END:variables

}
