/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TagEditor.java
 *
 * Created on Oct 8, 2010, 11:28:47 AM
 */

/**
 *
 * @author panic
 */
public class TagEditor extends javax.swing.JPanel {

    /** Creates new form TagEditor */
    public TagEditor() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text_field = new javax.swing.JTextField();
        item_list = new javax.swing.JList();
        ok_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();
        add_button = new javax.swing.JButton();
        remove_button = new javax.swing.JButton();

        text_field.setName("text_field"); // NOI18N

        item_list.setName("item_list"); // NOI18N

        ok_button.setText("OK"); // NOI18N
        ok_button.setToolTipText("Accept selection"); // NOI18N
        ok_button.setName("ok_button"); // NOI18N

        cancel_button.setText("Cancel"); // NOI18N
        cancel_button.setName("cancel_button"); // NOI18N

        add_button.setText("+"); // NOI18N
        add_button.setToolTipText("Add a new item"); // NOI18N
        add_button.setBorder(null);
        add_button.setName("add_button"); // NOI18N

        remove_button.setText("-"); // NOI18N
        remove_button.setToolTipText("Remove selected item"); // NOI18N
        remove_button.setBorder(null);
        remove_button.setName("remove_button"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(text_field, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(ok_button)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 82, Short.MAX_VALUE)
                        .add(cancel_button))
                    .add(layout.createSequentialGroup()
                        .add(add_button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(remove_button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(item_list, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 207, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(text_field, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(item_list, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 199, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(15, 15, 15)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(add_button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(remove_button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 30, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(ok_button)
                    .add(cancel_button))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton add_button;
    public javax.swing.JButton cancel_button;
    public javax.swing.JList item_list;
    public javax.swing.JButton ok_button;
    public javax.swing.JButton remove_button;
    public javax.swing.JTextField text_field;
    // End of variables declaration//GEN-END:variables

}
